export const tools = [
  { name: "Figma",    category: "UI Design",           color: "#F24E1E" },
  { name: "Framer",   category: "Prototyping",          color: "#0099FF" },
  { name: "VS Code",  category: "Coding",               color: "#007ACC" },
  { name: "Cursor",   category: "AI Development",       color: "#FFFFFF" },
  { name: "Claude",   category: "AI Workflows",         color: "#FF6B00" },
  { name: "Next.js",  category: "Frontend Framework",   color: "#FFFFFF" },
  { name: "React",    category: "UI Library",           color: "#61DAFB" },
  { name: "Tailwind", category: "Styling",              color: "#38BDF8" },
  { name: "GitHub",   category: "Version Control",      color: "#FFFFFF" },
  { name: "Notion",   category: "Documentation",        color: "#FFFFFF" },
  { name: "Python",   category: "Scripting",            color: "#3776AB" },
  { name: "GSAP",     category: "Animation",            color: "#88CE02" },
  { name: "Miro",     category: "Collaboration",        color: "#FFDD00" },
  { name: "Postman",  category: "API Testing",          color: "#FF6C37" },
  { name: "SQL",      category: "Database",             color: "#336791" },
]
