export const tools = [
  { name: "Figma", active: true },
  { name: "Framer", active: true },
  { name: "Notion", active: true },
  { name: "VS Code", active: true },
  { name: "Cursor", active: true },
  { name: "Miro", active: true },
  { name: "Postman", active: true },
  { name: "GitHub", active: true },
  { name: "Next.js", active: true },
  { name: "React", active: true },
  { name: "Python", active: true },
  { name: "SQL", active: true },
  { name: "GSAP", active: true },
  { name: "Tailwind", active: true },
  { name: "n8n", active: true },
  { name: "Claude", active: true },
]

// Fixed hex grid layout — tool cells interleaved with empty cells
// Order ensures visual distribution across honeycomb
export const hexGrid = [
  { name: "Figma", active: true },
  { name: "", active: false },
  { name: "Framer", active: true },
  { name: "Notion", active: true },
  { name: "", active: false },
  { name: "VS Code", active: true },
  { name: "", active: false },
  { name: "Cursor", active: true },
  { name: "Miro", active: true },
  { name: "", active: false },
  { name: "Postman", active: true },
  { name: "", active: false },
  { name: "GitHub", active: true },
  { name: "", active: false },
  { name: "Next.js", active: true },
  { name: "React", active: true },
  { name: "", active: false },
  { name: "Python", active: true },
  { name: "", active: false },
  { name: "SQL", active: true },
  { name: "", active: false },
  { name: "GSAP", active: true },
  { name: "", active: false },
  { name: "Tailwind", active: true },
  { name: "", active: false },
  { name: "n8n", active: true },
  { name: "", active: false },
  { name: "Claude", active: true },
  { name: "", active: false },
  { name: "", active: false },
  { name: "", active: false },
  { name: "", active: false },
  { name: "", active: false },
  { name: "", active: false },
  { name: "", active: false },
]
